### ISSUE TITLE
如何保证bark自建服务器的安全性呢？岂不是人人都可以用别人建的服务器？

### ISSUE THREAD

**Issue by wlwllbj** [Finb/bark-server#100]
rt，客户端注册只需要添加ip，这样别人猜到你的服务器地址，不就可以免费用了吗？

**Comment by mritd** [comment]
你可以在启动时设置用户名和密码来启用 Basic Auth 认证

https://github.com/Finb/bark-server/blob/master/route_auth.go

**Comment by wlwllbj** [comment]
不好意思，新手
我在docker中运行的怎么设置账号密码？需要重新编译吗？
感谢

**Comment by mritd** [comment]
docker 的运行参数 加上选项就行:

```sh
docker run -p 8080:8080 finab/bark-server bark-server --user admin --password your_passwd
```

具体的 docker 参数，例如如何保持后台运行以及文件挂载请参考 docker 文档。

**Comment by wlwllbj** [comment]
客户端 添加私有服务器哪里怎么填写呢？现在发送消息 提示 i am a teapot

**Comment by Finb** [comment]
客户端直接填对应的服务器地址，和没加验证的普通服务器一样。

发送时需要加上basic auth，具体怎么操作网上搜搜教程

**Comment by anwen-anyi** [comment]
> 你可以在启动时设置用户名和密码来启用 Basic Auth 认证
> 
> https://github.com/Finb/bark-server/blob/master/route_auth.go

😹 哎妈呀..回来考古...之前部署来着然后搬家重新部署..找这个方法可算是一顿好找哈哈 找了挺久 就是想不起在哪儿来着，建议开发者大大把这个链接或者文章加进使用说明 哈哈
