### ISSUE TITLE
新版本服务端异常，连接不上

### ISSUE THREAD

**Issue by lanqsh** [Finb/bark-server#102]
Bump v2.0.3貌似ping不通服务器，所有端口都是开放的，用tcpdump抓包能看到其他网络发送到8080端口的数据，应该不是防火墙的原因
![1640679239(1)](https://user-images.githubusercontent.com/12372700/147544616-ba93b944-cda6-4318-8537-001df84a6e91.png)
![image](https://user-images.githubusercontent.com/12372700/147545026-354044c1-4004-452b-b060-16acf2325152.png)

**Comment by Finb** [comment]
2.0.3 与上个版本没有啥区别，只是兼容了参数的处理
你服务器能 ping 通的话 程序就没问题的

你检查下域名是否正确解析到服务器 ，反代服务器是否正常反代 或其他的问题

**Comment by Finb** [comment]
也可以下载旧版本的后端程序使用
https://github.com/Finb/bark-server/releases/tag/v2.0.1
