### ISSUE TITLE
feat: allow setting to custom timezone

### ISSUE THREAD

**Issue by harryzcy** [Finb/bark-server#120]
Golang 支持使用 `TZ` 环境变量更改时间 ([source](https://go.dev/src/time/zoneinfo.go#L74))，如 `TZ=Asia/Shanghai`

目前 `Dockerfile` 中直接把 `/etc/localtime` 改成了 `/usr/share/zoneinfo/Asia/Shanghai`。但时区的设置在运行时用环境变量更好一些，只需要把 host 的 zoneinfo 文件映射进去。

e.g.

```shell
docker run -dt --name bark -p 8080:8080 -v `pwd`/bark-data:/data \
           -v /usr/share/zoneinfo/:/usr/share/zoneinfo/ --env TZ=Asia/Shanghai \
           finab/bark-server
```

所以我觉得 `Dockerfile` 中可以不改时区，在 `REAME.md` 中进行说明。

**Comment by citizen233** [comment]
@harryzcy 我优化了，你提出的这个问题
