### ISSUE TITLE
POST请求 body 有限制

### ISSUE THREAD

**Issue by hans1980775481** [Finb/bark-server#123]
response Status :  500 Internal Server Error
response Headers :  map[Content-Length:[94] Content-Type:[application/json] Date:[Sun, 20 Mar 2022 07:17:44 GMT] Server:[Bark]]
response Body :  {"code":500,"message":"push failed: APNS push failed: PayloadTooLarge","timestamp":1647760664}

**Comment by usgate** [comment]
苹果服务器对请求有长度限制，非bug

**Comment by hans1980775481** [comment]
限制是多大呀？

**Comment by Finb** [comment]
现在大概是4KB， 由苹果推送接受的最大size为准
