### ISSUE TITLE
请问releases中v2 v3 v4是有什么区别

### ISSUE THREAD

**Issue by slinar** [Finb/bark-server#156]
请问releases中v2 v3 v4是有什么区别
![image](https://user-images.githubusercontent.com/41759351/179452456-33727e94-ea81-4bcd-ae3d-751de1bf5175.png)

**Comment by mritd** [comment]
[https://github.com/golang/go/wiki/MinimumRequirements#amd64](https://github.com/golang/go/wiki/MinimumRequirements#amd64)

<img width="912" alt="image" src="https://user-images.githubusercontent.com/13043245/179456830-2c908fbb-d39f-4647-9dc2-f7db429927be.png">

**简而言之: `v*` 越高, 可能会用到更新的 CPU 指令集, 在现代处理器上运行性能可能更好**

**Comment by slinar** [comment]
这样啊，谢谢！
