### ISSUE TITLE
希望能修改一个API的名字

### ISSUE THREAD

**Issue by qingmuhy** [Finb/bark-server#157]
device_key能不能改成key，在一些软件里对于下划线的处理不怎么好会导致下划线被吃掉而导致错误。（curl正常，但哪吒探针里不能正常显示。）

**Comment by qingmuhy** [comment]
原来是空格问题，大伙还是慎开issue。

**Comment by mritd** [comment]
大部分软件对下划线和短横线处理都不会有太大问题，反而有时候一些驼峰规则可能会被转译等。所以目前我比较倾向下划线🤪
