### ISSUE TITLE
通过自己用java实现的服务端推送，客户端没有保存通知

### ISSUE THREAD

**Issue by 5kywa1ker** [Finb/bark-server#17]
增加isArchive=1参数 也不能保存，但是通过本项目的服务端推送，就能保存，
请问这是什么原因？

**Comment by Finb** [comment]
可能缺少了 "mutable-content":1，

在我的实现里是这行代码
https://github.com/Finb/bark-server/blob/19fe79ae4267957a10e389e529ce756d120f8564/server.go#L229

这个字段的一个作用是推送到达设备时，会先执行推送扩展里的代码再显示推送
保存推送的代码是在这个时候执行的

**Comment by 5kywa1ker** [comment]
> 可能缺少了 "mutable-content":1，
> 
> 在我的实现里是这行代码
> https://github.com/Finb/bark-server/blob/19fe79ae4267957a10e389e529ce756d120f8564/server.go#L229
> 
> 这个字段的一个作用是推送到达设备时，会先执行推送扩展里的代码再显示推送
> 保存推送的代码是在这个时候执行的

感谢老哥！ 已解决。
