### ISSUE TITLE
你好，我这边基于Go版做了一个Java版的Bark Server

### ISSUE THREAD

**Issue by hotlcc** [Finb/bark-server#170]
你好，我这边基于Go版做了一个Java版的Bark Server，可以加下友链吗？
https://gitee.com/hotlcc/java-bark-server

另外我这边的server目前遇到一个问题，消息在前台后台都能接收，但是在APP中的列表不展示，这个您知道是什么原因吗？

**Comment by Finb** [comment]
应该是缺少配置 MutableContent，不是这种类型的推送客户端收到后不能执行代码，也就不能保存推送了。
https://github.com/Finb/bark-server/blob/bfe0f28df369e7cda92e12311e4409e6148ad460/apns/apns.go#L106

**Comment by hotlcc** [comment]
> 

解决了，果然是这样
