### ISSUE TITLE
旁路由模式下docker无法通过外网访问

### ISSUE THREAD

**Issue by sean908** [Finb/bark-server#171]
使用手册中docker用法的基本命令
`docker run -dt --name bark -p 8080:8080 -v `pwd`/bark-data:/data finab/bark-server`
结果发现内网`curl`可以正常返回200, 但是公网访问失败, 通过端口扫描也显示容器放开的端口是关闭状态

在命令中加用`--net=host`可以实现公网访问

所以容器使用桥接网络时是否还需要加配什么呢?

PS: 跑容器的是一台旁路由

**Comment by Finb** [comment]
原因很多， 建议用类似“Docker端口映射外部无法访问”的关键字去搜一下，或者你就简单的用 host 网络
