### ISSUE TITLE
提示 certificate signed by unknow authority

### ISSUE THREAD

**Issue by louisanna** [Finb/bark-server#19]
将bark server直接部署到树莓派执行后，手机端发送消息测试 树莓派提示certificate signed by unknow authority

**Comment by Finb** [comment]
安装一下 GeoTrust Global CA 根证书试试。

从这里下载
https://www.geotrust.com/resources/root-certificates/
或
https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem

**Comment by louisanna** [comment]
我找不到安装命令

**Comment by omnjpa27516** [comment]
同样的问题不知道怎么解决…… @Finb

**Comment by omnjpa27516** [comment]
老版本同样的问题，昨天新的二进制文件是损坏的 @mritd

**Comment by louisanna** [comment]
> 
> 
> 老版本同样的问题，昨天新的二进制文件是损坏的 @mritd
我已经解决了 你呢

**Comment by mritd** [comment]
@louisanna @omnjpa27516 已经重新上传

**Comment by louisanna** [comment]
> @louisanna @omnjpa27516 已经重新上传

v1.0.2 运行提示-bash: ./bark-server_linux_arm: cannot execute binary file: Exec format error

**Comment by mritd** [comment]
@louisanna 请提供你的平台环境信息

**Comment by louisanna** [comment]
> @louisanna 请提供你的平台环境信息
Linux raspberrypi 5.4.51-v7+
 树莓派3b+

**Comment by mritd** [comment]
@louisanna 重传了一下 应该好了，你再试试

**Comment by zgzh** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596

wget --no-check-certificate -c https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem   \
    && mkdir /usr/local/share/ca-certificates/extra                                                                       \
    && mv GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/extra/GeoTrust_Global_CA.crt                            \
    && update-ca-certificates
