### ISSUE TITLE
关于Post请求

### ISSUE THREAD

**Issue by lovelykd** [Finb/bark-server#20]
目前的Get和Post请求都是将title/body/category等内容放在URL里面，我感觉对于Post请求，将它们封装为json payload更为合适
```
curl -d '{"title":"123", "body": "hello world"}' -H "Content-Type: application/json" -X POST https://api.day.app/:key/
```

**Comment by mritd** [comment]
@Finb 我要不要彻底重写一下？
@lovelykd 这个锅是 @Finb 的

**Comment by Finb** [comment]
title/body 除了可以放在 path 和 query 里
也能放在 POST Data 里的
```
curl -d 'title=123&body=hello world'  -X POST https://api.day.app/:key/
```

**Comment by lovelykd** [comment]
了解，谢谢你们的回复

**Comment by mritd** [comment]
其实我一直觉得应该换个正经的 web 框架，轻量级的 router 啥的 😅

**Comment by DarrenSong** [comment]
> 目前的Get和Post请求都是将title/body/category等内容放在URL里面，我感觉对于Post请求，将它们封装为json payload更为合适
> 
> ```
> curl -d '{"title":"123", "body": "hello world"}' -H "Content-Type: application/json" -X POST https://api.day.app/:key/
> ```

-X 后面的内容不需要加引号吗？
