### ISSUE TITLE
【如何限制未知设备连接到服务器】

### ISSUE THREAD

**Issue by Whichbfj28** [Finb/bark-server#205]
1、【如何限制未知设备连接到服务器】
现在的好像是搭建好了后 知道服务器地址的就可以直接使用。没有任何的密匙或者验证措施

**Comment by Finb** [comment]
#100

**Comment by Whichbfj28** [comment]
docker-compose的话应该怎么填写。使用环境变量-e 吗？
或者有没有完整服务器支持的配置文件代码。

**Comment by Whichbfj28** [comment]
或者我表达有误。我想问的是。bark服务端能否支持简单的密匙验证即可。。不用账号密码什么的。
这样发送的时候也复杂。只需要简单几个字符验证下即可。之前的时候可以通过设置nginx反代 /fdsagroew 来自定义密匙。
但是现在新版本好像无法使用这个功能。直接400错误。

**Comment by Whichbfj28** [comment]
找到了变通的方法、用nginx反代。


    location /123456/ {
          #这个123456改成自己的密匙，即可。访问的时候就是。测试：https://bark.com/123456/ping
        proxy_pass http://localhost:8080/;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_redirect off;
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP         $remote_addr;

    }
