### ISSUE TITLE
请问下自己搭建的网址推送不了。是什么原因呢？

### ISSUE THREAD

**Issue by asdfvv** [Finb/bark-server#21]
请问下大佬，自己搭建的文字可以推，网址就不能推。
带“/”符号的推送什么自己换行，如home/test,会变成一行home，一行test。只能复制到test
听说要转换字符吗？请问下怎么设置？
谢谢

**Comment by Finb** [comment]
需要给参数URL编码，否则如果参数中包含 / 会破坏URL结构 

例如
```swift
//给参数URL编码一下就行（各语言有不同的URL编码方法，方法名可能不一样）。
var url:String = "https://api.day.app/yourkey/" + "home/test".encodeURIComponent();   

//最后URL长这样
printf(url);  //https://api.day.app/yourkey/home%2ftest/

// 如果不编码则会产生歧义
// https://api.day.app/yourkey/home/test/
// 服务器会以为你请求的是 https://api.day.app/yourkey/{title}/{body}/  
// 自然就会分两行显示了，一行粗体title ，一行常规字体body

```

**Comment by asdfvv** [comment]
谢谢大佬解答，不过我是小白一个。
是不是要在哪加个参数？我用docker搭建的

**Comment by Finb** [comment]
服务端是正常的，是因为你拼的请求URL本身有问题，你可以去查一些 URL编码 相关的文章看一看

**Comment by asdfvv** [comment]
好的，谢谢大佬。我在去试试

**Comment by airdge** [comment]
> 服务端是正常的，是因为你拼的请求URL本身有问题，你可以去查一些 URL编码 相关的文章看一看
> 
> 或者
> 你不用把参数拼在URL路径里，用下面的格式去发推送
> [https://api.day.app/yourkey/?body={你要推送的内容}](https://api.day.app/yourkey/?body=%7B%E4%BD%A0%E8%A6%81%E6%8E%A8%E9%80%81%E7%9A%84%E5%86%85%E5%AE%B9%7D)

对于字符串中包含两个/时会出错
home%2ftesthome%2ftest
这种会被识别成
推送标题: testhome
推送内容: test
