### ISSUE TITLE
转义问题

### ISSUE THREAD

**Issue by malsony** [Finb/bark-server#215]
大家好！我将信息用Bash发送给服务器的时候是这样的：
`https://MYHOST/PATH/[Title]/[Body Text]`

`curl "https://MYHOST/PATH/$SMS_1_NUMBER/$SMS_1_TEXT"`

问题是我的Body Text（即$SMS_1_TEXT）中可能有这个“/”斜杠，不知道我应该怎样改呢？谢谢！

**Comment by Finb** [comment]
SMS_1_TEXT URL编码一下再拼接

malsony ***@***.***>于2023年5月6日 周六15:13写道：

**Comment by malsony** [comment]
收到，已解决，谢谢！
