### ISSUE TITLE
使用APNs Provider API

### ISSUE THREAD

**Issue by rankjie** [Finb/bark-server#22]
目前在写一个bark-server的Node.js版本，方便其他写前端比较顺手的朋友集成bark推送到自己的项目中。

看到Finb提供的还是p12的证书，好像没有使用「新」的APNs Provider API。因为我这边用到的APNs包都只支持了APNs Provider API，老的cert-key模式已经完全移除...所以请问是否考虑换用新的APNs协议？

切换应该没有什么特别要处理的地方，bark-server使用的apns2包已经支持，只需要到苹果开发者网站申请.p8证书，再在初始化apns2时提供下keyId和teamId即可。

换到新的协议最大的好处是不用再定期更新证书了。

参考： <https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html>

**Comment by jjss520** [comment]
支持支持

**Comment by mritd** [comment]
@Finb

**Comment by Finb** [comment]
感谢提醒！！！
下面是证书的下载链接和所需的key

https://github.com/Finb/bark-server/releases/download/v1.0.2/AuthKey_LH4T9V5U4R_5U8LBRXG3A.p8
KeyID: LH4T9V5U4R
TeamID: 5U8LBRXG3A
