### ISSUE TITLE
如何更换p8证书

### ISSUE THREAD

**Issue by BinBear** [Finb/bark-server#229]
自己服务器部署，如何配置证书为自己应用的 p8证书 呢

**Comment by Finb** [comment]
这里替换成你的证书
https://github.com/Finb/bark-server/blob/6a268f17a8e6e76d9b87c7509234428afbb13110/apns/apns_certs.go#L4

这里也要同步替换成你账号的
https://github.com/Finb/bark-server/blob/6a268f17a8e6e76d9b87c7509234428afbb13110/apns/apns.go#L31

**Comment by BinBear** [comment]
再麻烦问下，这个 topic 是啥呢，keyId 跟 teamId 是 AuthKey_xxx.p8 中的，这个知道，但是topic 不太明白，想请问下，谢谢

**Comment by Finb** [comment]
就是 APP 的 bundle id ，这个是唯一的，如果你要用你的账号打包需要更换一个ID。

另外如果你对iOS推送不熟悉，你还得注意 沙盒坏境和线上环境
https://github.com/Finb/bark-server/blob/6a268f17a8e6e76d9b87c7509234428afbb13110/apns/apns.go#L74

建议最好先找个iOS推送对接的教程看看，知道大概流程再来改这边的代码

**Comment by BinBear** [comment]
好的
