### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by secwang** [Finb/bark-server#24]
当 content中带%号的时候，会出现400 Bad Request⏎

**Comment by secwang** [comment]
空格，%，都会造成无返回的400 bad request

**Comment by Finb** [comment]
请求时如果URL中有特殊字符，为了防止特殊字符破坏URL结构，需要对内容URL编码一下
```
//例如
https://api.day.app/yourkey/%    %
//需要对推送内容进行URL编码
https://api.day.app/yourkey/%25++++%25
```

**Comment by secwang** [comment]
https://api.day.app/token/title/10%

**Comment by secwang** [comment]
按%编码成%25 之后应该是没问题的，有些encoding会format成%%的格式，这时候也会出问题。
