### ISSUE TITLE
私有部署服务每次调用都会触发两次

### ISSUE THREAD

**Issue by aisin** [Finb/bark-server#248]
私有部署服务每次调用都会触发两次，看日志也是同时产生两次请求。

<img width="958" alt="image" src="https://github.com/Finb/bark-server/assets/2437475/332606c6-2c75-4ba2-8c7b-c211a267207f">

**Comment by Finb** [comment]
这种一般就是请求了两次，你要查一下整个请求链路上哪个环节请求了两次。

**Comment by aisin** [comment]
尝试了下在浏览器中请求会触发两次，应该是我自身环境的问题，使用 postman 请求正常。感谢~
