### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by fdddf** [Finb/bark-server#25]
failed to run docker-compose with latest docker image, it outputs:

```
Starting bark-server ... done
Attaching to bark-server
bark-server    | standard_init_linux.go:211: exec user process caused "exec format error"
```

arm64 on ubuntu

**Comment by mritd** [comment]
Sorry, the arm version of docker image is not currently available.
This week I will rebuild the docker image through buildx.

**Comment by mritd** [comment]
@fdddf Now you can run it with `mritd/bark-server` image temporarily, we will push to `finb/bark-server` later.

**Comment by mritd** [comment]
@Finb Please use the `make buildx` command to rebuild the docker image. You may need to enable the docker buildx feature according to the documentation. Good luck.

**Enable docker experimental feature:**

```sh
cat > /etc/docker/daemon.json <<EOF
{
    "experimental": true
}
EOF

systemctl restart docker

# if it enabled, the version command will print "true"
docker version -f '{{.Server.Experimental}}')
```

Docs: [https://github.com/docker/cli/blob/master/experimental/README.md#use-docker-experimental](https://github.com/docker/cli/blob/master/experimental/README.md#use-docker-experimental)

**Install buildx command:**

```sh
# create plugin dir
mkdir -p ~/.docker/cli-plugins/

# download buildx cmd
wget https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
chmod a+x ~/.docker/cli-plugins/docker-buildx
```

Docs: [https://github.com/docker/buildx/blob/master/README.md#installing](https://github.com/docker/buildx/blob/master/README.md#installing)
