### ISSUE TITLE
Bark能不能设置白名单

### ISSUE THREAD

**Issue by Hello-XPH** [Finb/bark-server#267]

**Comment by Hello-XPH** [comment]
比如说那些ip不被ban

**Comment by Finb** [comment]
这个最好用防火墙之类的自己配置规则

**Comment by Hello-XPH** [comment]
就内网使用，还是会导致404的出现

**Comment by Hello-XPH** [comment]
还是希望可以设置白名单

**Comment by Finb** [comment]
bark-server 不会 ban ip，没有这个功能。404一般是你URL拼错了，检查特殊字符是否URL编码

**Comment by Hello-XPH** [comment]
[推送使用次数限制](https://bark.day.app/#/faq?id=%e6%8e%a8%e9%80%81%e4%bd%bf%e7%94%a8%e6%ac%a1%e6%95%b0%e9%99%90%e5%88%b6)
正常请求（HTTP状态码为200）无任何限制。
但如果在5分钟内超过1000次错误请求（HTTP状态码为400 404 500）IP会被 BAN 24小时

**Comment by Hello-XPH** [comment]
这个是你自己写的，会被BAN24小时的

**Comment by Hello-XPH** [comment]
为什么会错误这么多测试我也不太清除，

**Comment by Finb** [comment]
这个是我服务器防火墙规则，因为是公共服务器限制下滥用，和bark-server没有关系的

**Comment by Finb** [comment]
已经回答了 404一般是你URL拼错了，检查URL中的特殊字符

**Comment by Hello-XPH** [comment]
好吧，不是404 是400刚刚写错了

**Comment by Finb** [comment]
400 也是

**Comment by Hello-XPH** [comment]
就访问了ip:8080 也是400 普通都没有写

**Comment by Hello-XPH** [comment]
重新安装docker 就好了
