### ISSUE TITLE
在现有的nginx下新建 location 通过nginx的默认端口访问报错

### ISSUE THREAD

**Issue by channerchen** [Finb/bark-server#27]
{"code":400,"data":null,"message":"找不到 Key 对应的 DeviceToken, 请确保 Key 正确! Key 可在 App 端注册获得。"}

信息如上 直接打开机器的8080端口没问题 
咋处理呢 已有自带的证书

**Comment by channerchen** [comment]
nginx配置如下

server {
        listen 80;
        listen 443 ssl;
        ssl_certificate     /usr/local/cert/4414204.pem;
        ssl_certificate_key /usr/local/44142044.key;
        server_name home.cc.online;
     
        location /bark {
            log_not_found on;
            proxy_pass http://127.0.0.1:8080;
            proxy_read_timeout 300;
            proxy_connect_timeout 300;
            proxy_redirect off;
            proxy_set_header Host              $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP         $remote_addr;
        }

**Comment by Finb** [comment]
```
location /bark/ {
     proxy_pass http://127.0.0.1:8080/;
}
```
改成这样试试

**Comment by channerchen** [comment]
> ```
> location /bark/ {
>      proxy_pass http://127.0.0.1:8080/;
> }
> ```
> 
> 改成这样试试

还是不可以呢~

**Comment by Finb** [comment]
@channerchen 你再将你完整的配置文件发一下我看看

**Comment by channerchen** [comment]
user  root;
daemon on;
master_process on;
worker_processes  4;
#worker_rlimit 4g;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
error_log  logs/error.log  info;

worker_rlimit_nofile 102400;
worker_rlimit_core   2G;
working_directory    /tmp;

pid        logs/nginx.pid;

events {
    use epoll;
    worker_connections  4096;
    multi_listen unix:/tmp/http 80;
    multi_listen unix:/tmp/rtmp 1935;

    dynamic_refresh_interval 5s;
    dynamic_domain_buckets   1001;
    resolver 114.114.114.114  valid=1m;
    resolver_timeout 30s;
}

#stream_zone buckets=1024 streams=4096;

#dynamic_conf conf/nginx_dynamic.conf 10;
#dynamic_log logs/dynamic.log info;

rtmp {
    log_format log_bandwidth '{"app":"$app","name":"$name","bitrate":$bitrate,"args":"$args","timestamp":$ntp,"ts":"$time_local","type":"$command","remote_addr":"$remote_addr","domain":"$domain"}';
    access_log logs/bandwidth.log log_bandwidth trunc=60s;

    server {
        listen 1935;
        serverid 000;
        out_queue 2048;
        server_name live.pingos.io;
        rtmp_auto_pull on;
        rtmp_auto_pull_port unix:/tmp/rtmp;
   
        application push {
            live on;
            push rtmp://127.0.0.1/live app=live;
        }

        application live {
           live_record on;
           live_record_path /vod/data/record;


            recorder r1{
                record all;
                record_path /vod/data/record;
                record_max_size 10240000K;
            }

            live on;
            hls on;
            hls_path /tmp/hls;
            hls_fragment 4000ms;
#            hls_max_fragment 10000ms;
            hls_playlist_length 12000ms;
            hls_type live;

            hls2 on;
            mpegts_cache_time 20s;

            hls2_fragment 2000ms;
            hls2_max_fragment 3000ms;
            hls2_playlist_length 6000ms;

            wait_key on;
            wait_video on;
            cache_time 1s;
            send_all on;
            low_latency off;
            fix_timestamp 2s;
# h265 codecid, default 12
            hevc_codecid  12;
        }
    }
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_X-Forwarded-For" "$http_X-Real-IP" "$host"';


    access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #reset_server_name www.test1.com www.test2.com;
    #gzip  on;

    upstream hlsm {
#        hash $remote_addr consistent;
        hash $arg_session consistent;
        # 这里需要注意，你要开几个进程，就要按这个规则写几条记录
        server unix:/tmp/http.0;
        server unix:/tmp/http.1;
        server unix:/tmp/http.2;
        server unix:/tmp/http.3;
    }

    server {
        listen 80;
        listen 443 ssl;
        ssl_certificate     /usr/local/pingos/cert/4414204.cn.pem;
        ssl_certificate_key /usr/local/pingos/cert/4414204.key;
        server_name home.chen.online;
        location /rtmp_stat {
            rtmp_stat all;
            rtmp_stat_stylesheet /stat.xsl;
        }

        location /xstat {
            rtmp_stat all;
        }

        location /bark {
#            log_not_found on;
            proxy_pass http://127.0.0.1:8080;
 #           proxy_read_timeout 300;
  #          proxy_connect_timeout 300;
   #         proxy_redirect off;
    #        proxy_set_header Host              $host;
     #       proxy_set_header X-Forwarded-Proto $scheme;
      #      proxy_set_header X-Real-IP         $remote_addr;
        }

        location /sys_stat {
            sys_stat;
        }
        location ~ .mp4$ {
            #root html;
            #mp4;
            root /vod;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header "Access-Control-Allow-Credentials" "true";
            add_header "Access-Control-Allow-Methods" "*";
            add_header "Access-Control-Allow-Headers" "Content-Type,Access-Token";
            add_header "Access-Control-Expose-Headers" "*";
        }
        location /vod {
            root /vod; 
            types {
                 application/vnd.apple.mpegurl m3u8;
                 video/mp2t ts;
             }
             add_header 'Access-Control-Allow-Origin' '*';
             add_header "Access-Control-Allow-Credentials" "true";
             add_header "Access-Control-Allow-Methods" "*";
             add_header "Access-Control-Allow-Headers" "Content-Type,Access-Token";
             add_header "Access-Control-Expose-Headers" "*";
        }

        location /control {
            rtmp_control all;
        }
         location /flv {
             flv_live 1935 app=live;
             add_header 'Access-Control-Allow-Origin' '*';
             add_header "Access-Control-Allow-Credentials" "true";
             add_header "Access-Control-Allow-Methods" "*";
             add_header "Access-Control-Allow-Headers" "Content-Type,Access-Token";
             add_header "Access-Control-Expose-Headers" "*";
         }
         location /ts {
             ts_live 1935 app=live;
             expires -1;
             add_header 'Access-Control-Allow-Origin' '*';
             add_header "Access-Control-Allow-Credentials" "true";
             add_header "Access-Control-Allow-Methods" "*";
             add_header "Access-Control-Allow-Headers" "Content-Type,Access-Token";
             add_header "Access-Control-Expose-Headers" "*";
         }
         location /hls {
            # Serve HLS fragments
             types {
                 application/vnd.apple.mpegurl m3u8;
                 video/mp2t ts;
             }
             root /tmp;
             expires -1;
             add_header Cache-Control no-cache;
             add_header 'Access-Control-Allow-Origin' '*';
             add_header "Access-Control-Allow-Credentials" "true";
             add_header "Access-Control-Allow-Methods" "*";
             add_header "Access-Control-Allow-Headers" "Content-Type,Access-Token";
             add_header "Access-Control-Expose-Headers" "*";
         }

        location /hlsm {
             hls2_live 1935 app=live;
             add_header 'Access-Control-Allow-Origin' '*';
             add_header Cache-Control no-cache;
             add_header "Access-Control-Allow-Credentials" "true";
             add_header "Access-Control-Allow-Methods" "*";
             add_header "Access-Control-Allow-Headers" "Content-Type,Access-Token";
             add_header "Access-Control-Expose-Headers" "*";
         }

         location /hls2 {
             proxy_buffering on;
             proxy_buffer_size 4k; 
             proxy_buffers 8 1M;
             proxy_busy_buffers_size 2M;
             proxy_max_temp_file_size 0;
             set $hls_args location=/hls2&scheme=$scheme;
#             if ($args) {
#                 set $hls_args $args&location=/hls2&scheme=$scheme;
#             }
             proxy_set_header Host $host:$server_port;
             rewrite ^/(.*)/(.*)\.(.*)$ /hlsm/$2.$3?$hls_args break;
             proxy_pass http://hlsm;
         }

         location / {
             chunked_transfer_encoding on;
             root html/;
         }
    }
}

**Comment by Finb** [comment]
@channerchen 
```
location /bark/   <----- 注意加上后面这个 /  {
     proxy_pass http://127.0.0.1:8080/;    <----- 注意加上后面这个 / 
}
```
我看了你发的，你好像改错了，我是想让你在这两个位置加上  / ，其他都不变

**Comment by channerchen** [comment]
改好了 改成这样就行了。 原来是这样啊。。

**Comment by mritd** [comment]
> 加了两个斜杠就行了，莫非是权限问题。 谢谢哈

不是... 代码框架不那么智能，后面我重写一下🤪

**Comment by channerchen** [comment]
> > 加了两个斜杠就行了，莫非是权限问题。 谢谢哈
> 
> 不是... 代码框架不那么智能，后面我重写一下🤪

哈哈哈 已经很好了。 多年运维经验没查来 实属自己大意了
