### ISSUE TITLE
推送服务器网址不支持带子路径的吗？必须是网站根目录？

### ISSUE THREAD

**Issue by derline** [Finb/bark-server#273]
app上添加带子路径的服务器网址时，会提示"填写的服务器无效，请重试!网络错误"，是什么原因？

**Comment by Finb** [comment]
一般是没配置好，建议自己自测一下，填的地址后面再加个  /register 看返回的和 https://api.day.app/register 是否一致

**Comment by derline** [comment]
确实，配置有误，已搞定。

**Comment by iamckun** [comment]
怎么配置的添加子路径
