### ISSUE TITLE
关于多设备消息推送

### ISSUE THREAD

**Issue by Akimio521** [Finb/bark-server#277]
我有多台设备登录了同一个AppleID，获取到的Device Token不同，在同一个bark-server注册了相同的key，但是Bark-server似乎指挥给最后一个注册key的设备发送消息，之前注册的设备就获取不到推送，有没有方法可以给所有相同key的设备推送消息
其实可以多设备注册不同的key，然后推送时分别推送给多个key，但感觉不太优雅（

**Comment by icetech233** [comment]
> 我有多台设备登录了同一个AppleID，获取到的Device Token不同，在同一个bark-server注册了相同的key，但是Bark-server似乎指挥给最后一个注册key的设备发送消息，之前注册的设备就获取不到推送，有没有方法可以给所有相同key的设备推送消息 其实可以多设备注册不同的key，然后推送时分别推送给多个key，但感觉不太优雅（

这个简单，自己改代码就行了

**Comment by IcedMango** [comment]
我也有类似的需求，但是我需要根据不同的分组来选择多设备的推送

比如说抢票的推送我要所有设备都能收到，工作相关的告警在工作时间推送到mac，非工作时间推送到手机

可以试试n8n这个流程引擎，目前满足了我的推送需求了

**Comment by Finb** [comment]
已支持多设备推送，（单key推多设备不支持）

用法：
```sh
curl -X "POST" "https://api.day.app/push" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "title": "Title",
  "body": "Body",
  "sound": "minuet.caf",
  "group": "test",
  "device_keys": ["key1", "key2", ... ]
}'
```
