### ISSUE TITLE
ios推送接口错误

### ISSUE THREAD

**Issue by epicmr** [Finb/bark-server#28]
Post https://api.push.apple.com/3/device/a1abbcefa6bb21c56520422cf0a7929283c9456b9c13967e2cf5b23dd9ae5476: remote error: tls: expired certificate"

**Comment by epicmr** [comment]
use docker

**Comment by Finb** [comment]
Update the image and restart the container.
Now the certificate will never expire.

**Comment by epicmr** [comment]
ok, thks
