### ISSUE TITLE
Python implement (WIP)

### ISSUE THREAD

**Issue by billzhong** [Finb/bark-server#3]
Hi,

I made a python version of bark server:
https://github.com/billzhong/py-bark
Currently, it should work like a drop-in replacement.
I will keep working on it when I have time.

**Comment by billzhong** [comment]
All bugs related to my python implementation should be fixed now. Thanks @ldsxp

**Comment by mritd** [comment]
good job 😜

**Comment by fengqi** [comment]
Go版本的编译后就一个单文件，资源占用，部署便捷性和跨平台应该都很有优势，为什么还要用python和node再实现一边呢，是为了练手吗？
