### ISSUE TITLE
副标题(subtitle)不显示

### ISSUE THREAD

**Issue by YokukYo** [Finb/bark-server#300]
bark-server: Fiber v2.52.5 || Bump v2.1.8
ios bark:1.4.5(3)
ios:18.2
当icon不为""(默认图标)时
subtitle就会不显示...
<img width="1285" alt="Screenshot 2024-12-17 084821" src="https://github.com/user-attachments/assets/eb346ed9-b84a-4185-bde8-079ad471cfc0" />
<img width="1135" alt="Screenshot 2024-12-17 085921" src="https://github.com/user-attachments/assets/1f9e6468-a8ae-43a9-af90-66045ef92442" />

![image](https://github.com/user-attachments/assets/a1e7b8b9-dd72-4fc5-8658-0ab6fcd35977)

**Comment by Finb** [comment]
感谢反馈，已修复。
将在下个APP版本更新修复
