### ISSUE TITLE
与苹果推送服务器传输数据失败【dock方式自建】

### ISSUE THREAD

**Issue by mhqschen** [Finb/bark-server#31]
level=error msg="Error:%!(EXTRA *url.Error=Post \"https://api.push.apple.com/3/device/32b4cfcd**4270a8d325ec56fa2c\": dial tcp: lookup api.push.apple.com on 127.0.0.11:53: read udp 127.0.0.1:55741->127.0.0.11:53: i/o timeout)"

**Comment by mhqschen** [comment]
发现问题了，怎么是127.0.0.11:53。。。求更新🤣

**Comment by mritd** [comment]
这个问题是由于你本地 DNS 解析失败造成的，对于比较新的系统，例如 Ubuntu 20，系统 DNS 回被 systemd-resolved 接管，这个地址正是 resolved 监听的地址

**Comment by mhqschen** [comment]
谢谢提醒，发现问题了。 vi /etc/sysctl.conf后net.ipv4.ip_forward = 1解决了。
