### ISSUE TITLE
docker方式自建 总是提示 400 ExpiredProviderToken

### ISSUE THREAD

**Issue by Coderzgh** [Finb/bark-server#32]
docker方式自建 总是提示 403 ExpiredProviderToken 不知道为什么 看服务端接收到请求了 日志显示也是 403 ExpiredProviderToken
老哥知道为啥嘛？

**Comment by Coderzgh** [comment]
已经解决了 重启就好了
问题参见:https://www.jianshu.com/p/4ce0412b50c3

**Comment by mritd** [comment]
> 已经解决了 重启就好了
> 问题参见:https://www.jianshu.com/p/4ce0412b50c3

似乎这种问题在前几年 cantos 系统上日常出现，后来我们生产切换到 Ubuntu 以后就再也没见过 😂

**Comment by Coderzgh** [comment]
一台俄罗斯三毛机 内存512M 10G HDD配置太低 主要原因还是因为配置太低造成的
