### ISSUE TITLE
Merge log lines as per requests

### ISSUE THREAD

**Issue by vt128** [Finb/bark-server#35]
For the log output of the server app, one or multiple log lines will be generated for single request. It's really confusing when multiple requests reach the server at the same.

Have you ever considered about merging them into one, or give them a request ID?

What about modern logger like [uber/zap](https://github.com/uber-go/zap)?

**Comment by mritd** [comment]
The V2 version has been switched to zap log, and the http framework log is also as consistent as possible with the zap log format.

> Note: This may not be the final log format.
![image](https://user-images.githubusercontent.com/13043245/108615362-5c48c780-743e-11eb-9a0b-94c3c56cbf39.png)

**Comment by vt128** [comment]
@mritd Thanks! Btw, what's the font of your console? It looks nice.
