### ISSUE TITLE
Log IP of Requester?

### ISSUE THREAD

**Issue by vt128** [Finb/bark-server#36]
I use self-hosted bark server, and sometimes I received some strange notifications after I sent single one. And I didn't know who did this or watched on my network traffic.

Can you please add IP address of the requests in logging, so everyone can get more details about the requester/device sent the request?

```log
INFO[2021-02-07 03:23:04] 200 AE11B12A-D229-D4BC-2E26-CD8E591D37A9
INFO[2021-02-07 03:23:08]  ==========================
INFO[2021-02-07 03:23:08] key:  XXXXXXXXXXXXXX
INFO[2021-02-07 03:23:08] category:
INFO[2021-02-07 03:23:08] title:
INFO[2021-02-07 03:23:08] body:  无推送文字内容
INFO[2021-02-07 03:23:08] params:  map[automaticallycopy:* copy:* sound:*]
INFO[2021-02-07 03:23:08]  ==========================
```

**Comment by SokaOfficial** [comment]
+1
