### ISSUE TITLE
Hello，about startup parameter problems

### ISSUE THREAD

**Issue by MEZboy** [Finb/bark-server#4]
when i try to start bark-server,it return 

> flag provided but not defined: -p
Usage of ./bark:
  -dev
    	develop推送，请忽略此参数，设置此参数为True会导致推送失败
  -ip string
    	http listen ip (default "0.0.0.0")
  -port int
    	http listen port (default 8080)

here is my start bash:
`nohup /root/barkServer/bark -l 0.0.0.0 -p 81 -d /root/barkServer > /root/barkServer/bark.log &`

can you help me to fix this problem,thx!

**Comment by Finb** [comment]
The problem has been fixed, you can re-download the program and try again

**Comment by MEZboy** [comment]
it solved my problem,thanks a lot,i'll close this issue.
