### ISSUE TITLE
最新的证书如何安装？

### ISSUE THREAD

**Issue by Oscar1011** [Finb/bark-server#40]
最新的链接在手机打开只会下载。不会提示安装证书，系统是iOS 13。

**Comment by Finb** [comment]
这个证书手机并不需要安装，是自己实现服务端程序时需要用的

**Comment by Oscar1011** [comment]
如果我直接使用docker 安装到自己的服务器，这个证书是不是 就不需要了。

> 这个证书手机并不需要安装，是自己实现服务端程序时需要用的

**Comment by Finb** [comment]
对的

**Comment by Oscar1011** [comment]
ok，感谢
