### ISSUE TITLE
希望支持webdav保存日志，程序直接加载证书支持https。

### ISSUE THREAD

**Issue by xdeng** [Finb/bark-server#43]
希望支持webdav保存日志，程序直接加载证书支持https。

**Comment by mritd** [comment]
https 在 2.0.1 版本已经添加，webdav 功能由于不具有普遍性暂时不考虑添加到 server 中

**Comment by xdeng** [comment]
> https 在 2.0.1 版本已经添加，webdav 功能由于不具有普遍性暂时不考虑添加到 server 中

很多网盘，开源的都支持webdav的啊。。。

**Comment by mritd** [comment]
首先一个明确的是: **bark-server 是一个推送后端，对于推送后端服务来说应该在方便使用的同时尽可能的减少资源占用和提高性能。**

WebDAV 是一种存储服务，各种开源网盘支持 WebDAV 是很正常的，因为这是他们目标(实现一个网盘)的一部分 feature；

但是对于 bark-server 来说对接 WebDAV 意义不大，因为我们无法满足用户的挂载存储需求，今天可能是 WebDAV，明天会是  FTP 甚至是 NFS...... 而反观这些存储对于 bark-server 来说都不是其目标(一个推送服务器)的 feature，就比如说我们不可能在 bark-server 的文档里写到 "新特性: 支持 WebDAV" 一样，这货让人很困惑(一个推送服务器为什么跟 WebDAV 有关系)；

所以实现对接 N 种存储来说除了增加 bark-server 的不稳定和复杂度来说没有太大的意义。

**Comment by xdeng** [comment]
> 首先一个明确的是: **bark-server 是一个推送后端，对于推送后端服务来说应该在方便使用的同时尽可能的减少资源占用和提高性能。**
> 
> WebDAV 是一种存储服务，各种开源网盘支持 WebDAV 是很正常的，因为这是他们目标(实现一个网盘)的一部分 feature；
> 
> 但是对于 bark-server 来说对接 WebDAV 意义不大，因为我们无法满足用户的挂载存储需求，今天可能是 WebDAV，明天会是 FTP 甚至是 NFS...... 而反观这些存储对于 bark-server 来说都不是其目标(一个推送服务器)的 feature，就比如说我们不可能在 bark-server 的文档里写到 "新特性: 支持 WebDAV" 一样，这货让人很困惑(一个推送服务器为什么跟 WebDAV 有关系)；
> 
> 所以实现对接 N 种存储来说除了增加 bark-server 的不稳定和复杂度来说没有太大的意义。

😂 我说错了，是客服端支持webdav，现在客户端只支持iCloud同步日志。

**Comment by mritd** [comment]
@Finb 移动一下

**Comment by Finb** [comment]
现在的增量同步都是用的iCloud的API，应该不会继续支持webdav。
之后可能会加个导出备份吧
