### ISSUE TITLE
device key is empty

### ISSUE THREAD

**Issue by kuyoeku** [Finb/bark-server#45]
用的最新版的docker
使用时碰到提示,一直是这个提示。没有发送成功过。麻烦帮忙看一下。
`{
  "code": 400,
  "message": "device key is empty",
  "timestamp": 1614612016
}`

命令：
`curl -X "POST" "http://*****/push" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -u ':' \
     -d $'{
  "body": "te",
  "device_key": "vysnnvzowlzekezu",
  "title": "bleem",
  "category": "category"
}'`
日志：
`
 ┌───────────────────────────────────────────────────┐ 
 │                    Fiber v2.5.0                   │ 
 │               http://127.0.0.1:8080               │ 
 │                                                   │ 
 │ Handlers ............ 24  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
 └───────────────────────────────────────────────────┘ 

2021-03-01 15:20:15     INFO    10.39.1.141 -> [400] POST 330.801µs /push => /push {
    "body": "te",
    "device_key": "vysnnvzowlzekezu",
    "title": "bleem",
    "category": "category"
}`

**Comment by Finb** [comment]
现在应该解决了，你重新pull一下试试

**Comment by kuyoeku** [comment]
嗯，好了。
