### ISSUE TITLE
注册设备失败

### ISSUE THREAD

**Issue by liGuzhilan** [Finb/bark-server#49]
请求
register?devicetoken=bdfd19d89e66d7d1e265f2c240b68894326e37d1534735c6ec834af037d5ba87

返回：
{
"code": 400,
"message": "failed to get device token: failed to get [register] device token from database",
"timestamp": 1614847171
}

**Comment by Finb** [comment]
更新一下试试

**Comment by liGuzhilan** [comment]
> 更新一下试试

更新后可以了
