### ISSUE TITLE
Problems when using reverse proxy to enable HTTPS

### ISSUE THREAD

**Issue by dingyx99** [Finb/bark-server#5]
Hi, I met a problem when deploying by docker and reverse proxy to provide HTTPS support.

The app returned with an error code 0 when adding by https, but no problem when adding by http.

Maybe there's something wrong with the configuration of nginx, may you help me fix it? Many thanks.
![{3713834C-46DB-4213-B804-E78FBCCB5965} png](https://user-images.githubusercontent.com/11485117/54357256-a644a280-4698-11e9-9756-d8ebbffc17e8.jpg)

**Comment by Finb** [comment]
I'm not sure what the problem is, you can compare my configuration below.
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name api.day.app ;

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate ssl/day.app/day.app.cer;
    ssl_certificate_key ssl/day.app/day.app.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # modern configuration. tweak to your needs.
    ssl_protocols TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;


    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;

    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate ssl/ca.cer;

    location / {
       proxy_pass http://127.0.0.1:8081;
    }

}

server {
    listen 80 ;
    server_name api.day.app ;

    location / {
       proxy_pass http://127.0.0.1:8081;
    }

}
```

**Comment by dingyx99** [comment]
Thanks. I'll have a try and give you more feedback later. XD

**Comment by mritd** [comment]
@dingyx99 Please remove the `proxy_header Upgrade` config, this config is generally used to upgrade the http protocol to the websocket protocol(bark server is the standard http protocol).

If you don't know the nginx config file, it is recommended use the [Mozilla SSL Configuration Generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/) to generate the nginx configuration.

**Comment by dingyx99** [comment]
@mritd Thanks, but the problem didn't fix.😕Maybe there are something wrong with anything else in my server.
