### ISSUE TITLE
求教：docker兄弟容器访问bark-server如何配置呢？

### ISSUE THREAD

**Issue by LeanFly** [Finb/bark-server#52]
场景描述：

-  群晖docker下搭建了bark-server容器1，外网设备a可以注册并成功推送
-  群晖docker下搭建了另一个容器2，支持bark推送服务
-  求教，如何配置容器2的推送地址，让设备a可以收到推送通知呢？     
            _尝试填写docker容器互访的host.docker.internal方案失败
            尝试填写docker容器桥接的子网段地址172.x.x.x方案失败
            尝试填写路由器分配给群晖的192.168.x.x方案失败_

**Comment by mritd** [comment]
没太理解，如果你想让容器2访问容器1 只需要填写容器1的 ip 即可，但是这种并不可靠；推荐通过 `docker network create xxxxx` 方式创建专用 bridge，然后两个容器 join 进来通过容器名称互相访问即可。

**Comment by LeanFly** [comment]
> 没太理解，如果你想让容器2访问容器1 只需要填写容器1的 ip 即可，但是这种并不可靠；推荐通过 `docker network create xxxxx` 方式创建专用 bridge，然后两个容器 join 进来通过容器名称互相访问即可。

好的好的，多谢指导，我再搞搞
