### ISSUE TITLE
docker 部署的服务端 转发提示失败

### ISSUE THREAD

**Issue by wyap-echo** [Finb/bark-server#53]
IOS 客户端的测试链接时可以使用的
![photo_2021-04-02_22-55-35](https://user-images.githubusercontent.com/58325947/113427161-274d6e80-9407-11eb-857d-5e01f6e58174.jpg)

**Comment by Finb** [comment]
这很明显是推送URL有问题，你看下你URL是不是这种格式
https://host/key/title/body
