### ISSUE TITLE
window服务端部署，运行问题

### ISSUE THREAD

**Issue by ketergao** [Finb/bark-server#55]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x60d073]

goroutine 1 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
        crypto/x509/cert_pool.go:188
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc000131800,
d)
        crypto/x509/cert_pool.go:226 +0x2f3
github.com/finb/bark-server/v2/apns.init.0()
        github.com/finb/bark-server/v2/apns/apns.go:45 +0x1e5

windows部署的时候，报异常，不知道为什么?

**Comment by metrue** [comment]
@ketergao 

可以提供一下你的操作步骤么，我们可以尝试复现一下。

**Comment by mritd** [comment]
golang/go#16736

**Comment by mritd** [comment]
@ketergao 已修复

**Comment by ketergao** [comment]
这个貌似是go在window下 systemCertPool不可用导致了。
 感谢.

**Comment by mritd** [comment]
由于我们本身内置了 APNS CA，所以目前我们直接采用空 pool，理论上可以撑到将来 APNS 再次更换新 CA
