### ISSUE TITLE
IOS 1.1.5版本不支持自动复制，1.1.4正常

### ISSUE THREAD

**Issue by yyysuo** [Finb/bark-server#68]
IOS14.3越狱7P，在最新版本程序下无法自动复制文字到剪贴板，降级到1.1.4正常了，是最新版本的app移除了这项功能吗？》

**Comment by Finb** [comment]
是有这个问题，等会儿提交个修复版 1.1.7，大概明天可以更新

**Comment by yyysuo** [comment]
非常感谢您。

**Comment by Finb** [comment]
太客气啦
