### ISSUE TITLE
推送时常会返回HTTP500错误

### ISSUE THREAD

**Issue by BroHui** [Finb/bark-server#71]
我自己搭建了bark-server，最近时常会发生推送失败问题，想确认下是我这里的网络环境问题吗？

环境: docker image: finab/bark-server:v2.0.2

{'code': 500,
 'message': 'push failed: Post '
            '"https://api.push.apple.com/3/device/hiddenid": '
            'read tcp 172.19.0.4:37850->17.188.139.155:443: read: connection '
            'reset by peer',
 'timestamp': 1626782968}

大多数时候正常返回：
{"code":200,"message":"success","timestamp":1626782971}

**Comment by Finb** [comment]
不太确定 ，你的网络情况如何？

如果找不到原因，你可以在发送端做一个发送失败重试机制，失败了就重试几次

**Comment by BroHui** [comment]
> 不太确定 ，你的网络情况如何？
> 
> 如果找不到原因，你可以在发送端做一个发送失败重试机制，失败了就重试几次

查了一下，应该是苹果APNs的问题，需要自己处理一下。简单点要么走proxy，要么增加重试。

再次感谢开源这么好的方案！
