### ISSUE TITLE
关于API_V2的一些问题

### ISSUE THREAD

**Issue by Weiney** [Finb/bark-server#80]
https://github.com/Finb/bark-server/blob/master/docs/API_V2.md

文档内有介绍一个Category参数，没做过iOS开发，希望可以解释下这个参数的具体含义，因为我一直把这个参数当Group来使用。
后来发现并没有效果。我想使用Group字段对通知分组，但是V2的文档并没有Group这个参数。

我在源码找到可以在ExtParams加入一个Group参数来对消息进行分组，希望能够在文档进行补充说明

**Comment by Finb** [comment]
感谢提醒，之后会更新文档。
一般来说所有的自定义参数，都可以放在 ExtParams 里
Category 是用于对推送进行分类的，下拉推送时可以有不同的操作。现在只有一个默认的category就是下拉复制推送。
