### ISSUE TITLE
windows 启动后 提示 Cannot GET

### ISSUE THREAD

**Issue by xiongxuxx** [Finb/bark-server#83]
![image](https://user-images.githubusercontent.com/23415180/133933773-94b1793c-a6d1-4c5f-bae6-f85f30df485e.png)
访问http://127.0.0.1:8080 返回以下信息 
Cannot GET

阿里云的windows server 2019

返回是正常的.   
访问http://IP:8080  可以正常访问到
访问 https//  提示不安全 是要装证书吗  证书我看是.pm格式 需要自己转成.cert 在Windows 安装?

另外还有一个问题是  我更换服务器为自己IP地址后,换回官方服务器
key值 自动更换了 
但是原来的key值 请求   推送还是有反应的. 是正常的吗?

**Comment by athurg** [comment]
## Cannot GET /

正常的，因为/路径本来就没有业务逻辑，所以返回这个404错误信息。

## HTTPS

bark-server本身不提供HTTPS支持。需要自行实现HTTPS服务器，卸掉TLS协议后，以纯HTTP的形式转发到bark-server。如果你使用阿里云，那么阿里云的负载均衡器提供相关的功能。

代码库中的不是证书。而是密钥。是用于苹果APNS推送的认证，而非HTTPS的认证。

## 多个服务器同时有效

这个应该是正常的。key是自动生成的。重新换回后会生成一个新key。但是设备的信息（Device Token）不会发生改变。

当你从官方服务器更换到你自建服务器的时候。官方服务器并不知道你更换，因此也不会删除你的老key。所以会一直生效。

不过 @Finb 也许可以增加一个卸载提示，特别是官方服务器，换走后自动删除。一来数据隐私更有保障，另外节省官方服务器的资源。
