### ISSUE TITLE
能不能把参数改成，比如http://ip/token/参数/标题/内容

### ISSUE THREAD

**Issue by jjss520** [Finb/bark-server#85]
现在把参数放到最后面，很多推送的设置是直接这样http://ip/token/
想加参数的话http://ip/token/参数这样又和内容冲突

**Comment by Finb** [comment]
参数怎么会和内容冲突呀？
使用标准URL格式传递参数即可

**Comment by jjss520** [comment]
大佬，比如V2P的推送，他只需要一个http://ip/token/，如果我要加个分组http://ip/token/?group=groupName,这样，他的推送内容就是http://ip/token/?group=groupNam内容

**Comment by Finb** [comment]
只需将 “?group=groupNam内容” URL编码一下即可
最后是 http://ip/token/%3Fgroup%3DgroupNam%E5%86%85%E5%AE%B9

**Comment by jjss520** [comment]
> 只需将 “?group=groupNam内容” URL编码一下即可
> 最后是 http://ip/token/%3Fgroup%3DgroupNam%E5%86%85%E5%AE%B9

哦哦，原来要URL编码呀，好的，我马上试试

**Comment by jjss520** [comment]
大佬，再问一下，post下，比如分组声音这样应该怎么弄
{"title": `【$title$】`,"body": `$body$`,"group":"elecV2P"}
我这样不行，标题和内容都可以

**Comment by Finb** [comment]
@jjss520 
参数应该放到 
```
{"title": 【$title$】,"body": $body$, "ext_params": {"group":"elecV2P"}}
```

**Comment by jjss520** [comment]
> @jjss520
> 参数应该放到
> 
> ```
> {"title": 【$title$】,"body": $body$, "ext_params": {"group":"elecV2P"}}
> ```

谢谢，可以了

**Comment by jjss520** [comment]
推送自定义图标怎么没成功呢，服务端和客户端今天才更新的
https://11111/0000000000/自定义推送图标?icon=https://day.app/assets/images/avatar.jpg
直接这样测试的

**Comment by Finb** [comment]
软件里忘了写，这个特性需要iOS15

**Comment by jjss520** [comment]
> 软件里忘了写，这个特性需要iOS15

难怪搞了半天不行

**Comment by jjss520** [comment]
大佬，分段发送刻不容缓呀
HTTPError: Response code 431 (Request Header Fields Too Large)
好多推送都因为太长了失败
