### ISSUE TITLE
内容有emoji时发送会返回431

### ISSUE THREAD

**Issue by wenco** [Finb/bark-server#86]
Hi，我在使用docker自建时，推送内容有emoji文字就会返回下面的信息，需要怎么更改配置？
{"code":431,"message":"Request Header Fields Too Large","timestamp":1632886021}

**Comment by Finb** [comment]
和emoji无关，看提示是推送内容过长。
苹果推送 payload 大小限制为 4KB，如果你的文本过长就需要裁减掉掉一些。

**Comment by wenco** [comment]
同样的推送内容，在替换你的推送接口前可以正常推送，更换我docker自建就提示上面的问题，后面把推送内容中所有emoji删除就可以推送。目前使用ios15。

**Comment by wenco** [comment]
可能emoji太多导致超限了
