### ISSUE TITLE
Docker能否增加自定义端口参数呢？

### ISSUE THREAD

**Issue by fsnhljz** [Finb/bark-server#93]
可能我说得不明白，我用群晖的docker，希望使用host网络，但这个貌似定了是8080端口。如果可以环境变量自己填端口就好了
![Uploading WX20211017-132424.png…]()

**Comment by Finb** [comment]
docker run -dt --name bark -p 9999:8080 -v `pwd`/bark-data:/data finab/bark-server

使用docker自带的端口映射，例如上面的9999

**Comment by mritd** [comment]
> > docker run -dt --name bark -p 9999:8080 -v `pwd`/bark-data:/data finab/bark-server
> > 
> > 使用docker自带的端口映射，例如上面的9999
> 
> host网络下改端口映射无效，楼主应该是跟我一样想用ipv6，但是改bridge模式的ipv6很难。这个项目我查了下只能改main.go自己构建一个新镜像来改host网络默认端口。希望作者能花点时间适配一下留个改参数途径 `-e PORT=8081` 谢谢

可以使用 BARK_SERVER_ADDRESS 环境变量告诉 sever 需要监听哪个端口，参数默认值没记错是 0.0.0.0:8080

**Comment by Finb** [comment]
也可以改运行命令
```sh
docker run -dt --name bark --network host -v `pwd`/bark-data:/data finab/bark-server bark-server -addr 0.0.0.0:8081
```
