### ISSUE TITLE
push failed

### ISSUE THREAD

**Issue by liupcoder** [Finb/bark-server#94]
{"code":500,"message":"push failed: Post \"https://api.push.apple.com/3/device/f27f1b8195fad27fe14aec0effa709bac306af26437801783ca532231a434b42\": dial tcp: i/o timeout","timestamp":1634556119}

**Comment by Co2333** [comment]
same here

**Comment by Co2333** [comment]
turns out it is a dns error on my cloud machine

<img width="808" alt="截屏2021-10-31 下午12 15 11" src="https://user-images.githubusercontent.com/25259084/139567357-afe7c9cc-c536-4588-9f01-a415ad78e228.png">
